version: '3.9'

services:
  web:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ../:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  php-fpm:
    build: ./php
    volumes:
      - ../:/var/www/html
  mysqldb:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlroot123
    ports:
      - '8989:3306'
    volumes:
      - ./db/mysql:/var/lib/mysql